---
title: Errore del compilatore CS1017
ms.date: 07/20/2015
ms.prod: .net
ms.technology: devlang-csharp
ms.topic: article
f1_keywords: CS1017
helpviewer_keywords: CS1017
ms.assetid: e0902e8a-b042-4711-a8a6-83456a3f88cb
caps.latest.revision: "9"
author: BillWagner
ms.author: wiwagn
ms.openlocfilehash: 5170c43a4618348c2dea1a0dade2f6d6ddbeb2d2
ms.sourcegitcommit: bd1ef61f4bb794b25383d3d72e71041a5ced172e
ms.translationtype: MT
ms.contentlocale: it-IT
ms.lasthandoff: 10/18/2017
---
# <a name="compiler-error-cs1017"></a>Errore del compilatore CS1017
Le clausole catch non possono seguire la clausola catch generale di un'istruzione try  
  
 Un blocco `catch` che non accetta parametri deve essere l'ultimo in una serie di blocchi `catch` . Per altre informazioni sulle eccezioni, vedere [Exception Handling Statements](../../csharp/language-reference/keywords/exception-handling-statements.md).  
  
## <a name="example"></a>Esempio  
 L'esempio seguente genera l'errore CS1017:  
  
```  
// CS1017.cs  
using System;  
  
namespace x  
{  
    public class b : Exception  
    {  
    }  
  
    public class a  
    {  
        public static void Main()  
        {  
            try  
            {  
            }  
  
            catch   // CS1017, must be last catch  
            {  
            }  
  
            catch(b)  
            {  
                throw;  
            }  
        }  
    }  
}  
```
