---
title: Errore del compilatore CS1626
ms.date: 07/20/2015
ms.prod: .net
ms.technology: devlang-csharp
ms.topic: article
f1_keywords: CS1626
helpviewer_keywords: CS1626
ms.assetid: 3ba03383-eb24-4fd8-bf40-8b0f7d6baf0d
caps.latest.revision: "6"
author: BillWagner
ms.author: wiwagn
ms.openlocfilehash: 85411831781518117092f2462a01abf02b4ed927
ms.sourcegitcommit: bd1ef61f4bb794b25383d3d72e71041a5ced172e
ms.translationtype: MT
ms.contentlocale: it-IT
ms.lasthandoff: 10/18/2017
---
# <a name="compiler-error-cs1626"></a>Errore del compilatore CS1626
Impossibile produrre un valore nel corpo di un blocco try con una clausola catch  
  
 L'istruzione yield non è consentita in un blocco try se è presente una clausola catch associata al blocco try. Per evitare questo errore, spostare l'istruzione yield fuori dalla clausola catch.  
  
 L'esempio seguente genera l'errore CS1626:  
  
```  
// CS1626.cs  
using System.Collections;  
  
class C : IEnumerable  
{  
   public IEnumerator GetEnumerator()  
   {  
      try  
      {  
         yield return this;  // CS1626  
      }  
      catch  
      {  
  
      }  
   }  
}  
  
public class CMain  
{  
   public static void Main() { }  
}  
```
