---
title: Errore del compilatore CS1626
ms.date: 07/20/2015
f1_keywords:
- CS1626
helpviewer_keywords:
- CS1626
ms.assetid: 3ba03383-eb24-4fd8-bf40-8b0f7d6baf0d
ms.openlocfilehash: 3d24280006d77c807109723cd05d2836570fdc91
ms.sourcegitcommit: 3d5d33f384eeba41b2dff79d096f47ccc8d8f03d
ms.translationtype: MT
ms.contentlocale: it-IT
ms.lasthandoff: 05/04/2018
---
# <a name="compiler-error-cs1626"></a>Errore del compilatore CS1626
Impossibile produrre un valore nel corpo di un blocco try con una clausola catch  
  
 L'istruzione yield non è consentita in un blocco try se è presente una clausola catch associata al blocco try. Per evitare questo errore, spostare l'istruzione yield fuori dalla clausola catch.  
  
 L'esempio seguente genera l'errore CS1626:  
  
```csharp  
// CS1626.cs  
using System.Collections;  
  
class C : IEnumerable  
{  
   public IEnumerator GetEnumerator()  
   {  
      try  
      {  
         yield return this;  // CS1626  
      }  
      catch  
      {  
  
      }  
   }  
}  
  
public class CMain  
{  
   public static void Main() { }  
}  
```
